# ===================================================================
# Core Application Configuration
# ===================================================================
spring.application.name=ride
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/smr
spring.datasource.username=postgres
spring.datasource.password=Nagraj@2005
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Tells Hibernate explicitly how to map and execute PostGIS geometry functions natively
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Console logging setups (Crucial for tracking spatial queries during local testing)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_T5olh19H0rNb8k
razorpay.key.secret=YIS16TZNN4Jrx4eJ91oyCiih

app.security.jwt.public-key-path=classpath:keys/public.key

