# ===================================================================
# Core Application Configuration
# ===================================================================
spring.application.name=ride
server.port=8082

# ===================================================================
# Database Connection (PostgreSQL + PostGIS spatial support)
# ===================================================================
# Replace 'localhost:5432/smr_rides_db' with your target host and database name
spring.datasource.url=jdbc:postgresql://localhost:5432/smr
spring.datasource.username=postgres
spring.datasource.password=Nagraj@2005
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# JPA & Hibernate Configurations
# ===================================================================
# update: Automatically updates the database schema matching your entity changes without wiping data.
# (For a brand new database, use 'update' or 'create-drop' during development)
spring.jpa.hibernate.ddl-auto=update

# Tells Hibernate explicitly how to map and execute PostGIS geometry functions natively
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Console logging setups (Crucial for tracking spatial queries during local testing)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_T5olh19H0rNb8k
razorpay.key.secret=YIS16TZNN4Jrx4eJ91oyCiih

app.security.jwt.public-key-path=classpath:keys/public_key.key

spring.security.oauth2.resourceserver.jwt.secret-key-string=iUBhYezBVjvKy41I8UvQ1MRRCUJtNR1EaesjJMgAodU